name: CI Pipeline

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Pull Docker image from Docker Hub
        run:  docker pull israr08/static-website:v1
        
      - name: Run Docker Container
        run: docker run -d -p 81:80 --name codesentinelProject2 israr08/static-website:v1
        
      - name: Run Unit Tests
        run: |
          echo "Running Unit Test..."
          # Example test: check container is running
          docker ps | grep codesentinelProject2
      - name: Stop container
        if: always()
        run: docker stop codesentinelProject2 && docker rm codesentinelProject2
          
        
  
